// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/notivenl/uptime-kubernetes/pkg/config"
	"github.com/notivenl/uptime-kubernetes/pkg/process"
	v1 "k8s.io/api/networking/v1"
	"sync"
)

// Ensure, that InputMock does implement process.Input.
// If this is not the case, regenerate this file with moq.
var _ process.Input = &InputMock{}

// InputMock is a mock implementation of process.Input.
//
// 	func TestSomethingThatUsesInput(t *testing.T) {
//
// 		// make and configure a mocked process.Input
// 		mockedInput := &InputMock{
// 			InitFunc: func(configMoqParam *config.Config) error {
// 				panic("mock out the Init method")
// 			},
// 			ProcessFunc: func(ingress v1.Ingress, dataCh chan process.Data)  {
// 				panic("mock out the Process method")
// 			},
// 		}
//
// 		// use mockedInput in code that requires process.Input
// 		// and then make assertions.
//
// 	}
type InputMock struct {
	// InitFunc mocks the Init method.
	InitFunc func(configMoqParam *config.Config) error

	// ProcessFunc mocks the Process method.
	ProcessFunc func(ingress v1.Ingress, dataCh chan process.Data)

	// calls tracks calls to the methods.
	calls struct {
		// Init holds details about calls to the Init method.
		Init []struct {
			// ConfigMoqParam is the configMoqParam argument value.
			ConfigMoqParam *config.Config
		}
		// Process holds details about calls to the Process method.
		Process []struct {
			// Ingress is the ingress argument value.
			Ingress v1.Ingress
			// DataCh is the dataCh argument value.
			DataCh chan process.Data
		}
	}
	lockInit    sync.RWMutex
	lockProcess sync.RWMutex
}

// Init calls InitFunc.
func (mock *InputMock) Init(configMoqParam *config.Config) error {
	if mock.InitFunc == nil {
		panic("InputMock.InitFunc: method is nil but Input.Init was just called")
	}
	callInfo := struct {
		ConfigMoqParam *config.Config
	}{
		ConfigMoqParam: configMoqParam,
	}
	mock.lockInit.Lock()
	mock.calls.Init = append(mock.calls.Init, callInfo)
	mock.lockInit.Unlock()
	return mock.InitFunc(configMoqParam)
}

// InitCalls gets all the calls that were made to Init.
// Check the length with:
//     len(mockedInput.InitCalls())
func (mock *InputMock) InitCalls() []struct {
	ConfigMoqParam *config.Config
} {
	var calls []struct {
		ConfigMoqParam *config.Config
	}
	mock.lockInit.RLock()
	calls = mock.calls.Init
	mock.lockInit.RUnlock()
	return calls
}

// Process calls ProcessFunc.
func (mock *InputMock) Process(ingress v1.Ingress, dataCh chan process.Data) {
	if mock.ProcessFunc == nil {
		panic("InputMock.ProcessFunc: method is nil but Input.Process was just called")
	}
	callInfo := struct {
		Ingress v1.Ingress
		DataCh  chan process.Data
	}{
		Ingress: ingress,
		DataCh:  dataCh,
	}
	mock.lockProcess.Lock()
	mock.calls.Process = append(mock.calls.Process, callInfo)
	mock.lockProcess.Unlock()
	mock.ProcessFunc(ingress, dataCh)
}

// ProcessCalls gets all the calls that were made to Process.
// Check the length with:
//     len(mockedInput.ProcessCalls())
func (mock *InputMock) ProcessCalls() []struct {
	Ingress v1.Ingress
	DataCh  chan process.Data
} {
	var calls []struct {
		Ingress v1.Ingress
		DataCh  chan process.Data
	}
	mock.lockProcess.RLock()
	calls = mock.calls.Process
	mock.lockProcess.RUnlock()
	return calls
}
